In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# NumPy's main datatype is an ndarray (n-dimensional array)

a1 = np.array([1,2,3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 =np.array([[1,2.0,3.3],[4,5,6.5]])

a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype 

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
 a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# Create a dataframe from an NumPy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Create NumPy Arrays

In [20]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int64')

In [30]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
ones.dtype

dtype('float64')

In [32]:
type(ones)

numpy.ndarray

In [38]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
range_array = np.arange(0, 10, 2) 
range_array

array([0, 2, 4, 6, 8])

In [42]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[6, 6, 4, 2, 8],
       [0, 8, 7, 9, 8],
       [2, 0, 8, 3, 4]])

In [43]:
random_array.size

15

In [44]:
random_array.shape

(3, 5)

In [46]:
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.20621642, 0.89177521, 0.67135905, 0.42021771, 0.19055681],
       [0.13178265, 0.09290924, 0.83980223, 0.5531592 , 0.0736996 ],
       [0.01035321, 0.17601278, 0.58846146, 0.90278768, 0.28429215]])

In [47]:
random_array_2.size

15

In [48]:
random_array_2.shape

(3, 5)

In [50]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.62164655, 0.44890182, 0.70587521],
       [0.46815853, 0.92663854, 0.68990196],
       [0.04526994, 0.70476434, 0.31339016],
       [0.80524135, 0.20152873, 0.43290593],
       [0.75755306, 0.92948374, 0.88941862]])

In [66]:
# Pseudo-random numbers

np.random.seed(0)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4



array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [78]:
np.random.seed(0)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## 3. Viewing Arrays & Matrices

In [80]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a1

array([1, 2, 3])

In [84]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [85]:
a1[0]

1

In [86]:
a2[0]

array([1. , 2. , 3.3])

In [87]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [89]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7],
         [0, 1, 9, 9, 0]],

        [[4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1]],

        [[7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4],
         [4, 3, 4, 4, 8]]],


       [[[4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2],
         [4, 2, 0, 3, 2]],

        [[0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4]],

        [[6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2],
         [3, 2, 0, 8, 8]]]])

In [90]:
a4.shape


(2, 3, 4, 5)

In [91]:
a4.ndim

4

In [94]:
# Get the first 4 numbers of the innermost arrays

a4[:, :, :, :1]

array([[[[9],
         [5],
         [1],
         [0]],

        [[4],
         [2],
         [5],
         [4]],

        [[7],
         [7],
         [9],
         [4]]],


       [[[4],
         [0],
         [0],
         [4]],

        [[0],
         [2],
         [3],
         [1]],

        [[6],
         [0],
         [3],
         [3]]]])

## 4. Manipulating & Comparing arrays

### Arithmetic 

In [96]:
a1

array([1, 2, 3])

In [99]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [100]:
a1 + ones

array([2., 3., 4.])

In [101]:
a1 - ones

array([0., 1., 2.])

In [104]:
a1 * ones

array([1., 2., 3.])

In [103]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [105]:
a1

array([1, 2, 3])

In [106]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [107]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [108]:
a1 / ones

array([1., 2., 3.])

In [111]:
# floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [112]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [113]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [114]:
 np.add(a1, a2)

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [115]:
a1 % 2

array([1, 0, 1])

In [116]:
a1 / 2

array([0.5, 1. , 1.5])

In [117]:
 np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [118]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Performing the same operation on a number of things

In [120]:
listy_list = [1,2,3]

In [122]:
type(listy_list)

list

In [123]:
sum(listy_list)

6

In [124]:
a1

array([1, 2, 3])

In [125]:
sum(a1)

6

In [126]:
np.sum(a1)

6

#### use python methods on python datatypes and use np methods on np datatypes (ndarray)

In [129]:
# create a massive array
massive_array = np.random.random(100000)
massive_array.size

100000

In [130]:
massive_array[:10]

array([0.67530963, 0.22337143, 0.74435904, 0.48892904, 0.38805839,
       0.88669099, 0.73350055, 0.53682108, 0.86580175, 0.14591431])

In [134]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

24.8 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [135]:
np.mean(a2)

3.6333333333333333

In [136]:
np.max(a2)

6.5

In [137]:
np.min(a2)

1.0

In [138]:
 np.std(a2)

1.8226964152656422

In [139]:
np.var(a2)

3.3222222222222224